name: honestorage
description: An honest and offline password storage
publish_to: 'none'

version: 0.0.1+1


environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2
  formz: ^0.4.1

  fluttertoast: ^8.1.3
  flutter_focus_watcher: ^2.0.0
  reorderables: ^0.6.0

  flutter_markdown: ^0.6.14
  markdown_editable_textinput: ^2.2.0
  
  shared_preferences: ^2.0.17
  pointycastle: ^3.6.2
  json_annotation: ^4.8.0
  js: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
